version: '3.8'

volumes:
  ode_modules: {}
  mongo_data: {}
  mongo_log: {}

networks:
  app-network:
    driver: bridge

services:
  redis-atemu:
    container_name: redis-atemu
    image: redis:alpine
    ports:
      - 6380:6379
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
      - ./redis_data:/data
    command: redis-server /usr/local/etc/redis/redis.conf
    environment:
      - HOST=redis
    networks:
      - app-network
    restart: always


  mongo:
    image: mongo:7.0.14
    container_name: mongo_atemu
    networks:
      - app-network
    environment:
      - HOST=mongo
    volumes:
      - mongo_data:/data/db
      - mongo_log:/data/log
    ports:
      - 27018:27017
   

  onchain-worker:
    container_name: onchain-worker-atemu
    build:
      context: .
      args:
        PKG: 'onchain-worker'
      dockerfile: Dockerfile
    networks:
      - app-network
    env_file:
      - .env
    restart: always
    ports:
      - 8090:8090
    depends_on:
      - mongo
      - redis-atemu

   

  onchain-queue:
    container_name: onchain-queue-atemu
    build:
      context: .
      args:
        PKG: 'onchain-queue'
      dockerfile: Dockerfile
    networks:
      - app-network
    env_file:
      - .env
    restart: always
    ports:
      - 8089:8089
    depends_on:
      - mongo
      - redis-atemu
    
   
  atemu-service:
    container_name: api-service-atemu
    build:
      context: .
      args:
        PKG: 'api-service'
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - .:/app
    ports:
    - 8080:8080
    - 5050:5050
    - 5051:5051
    networks:
      - app-network

