
services:
  redis:
    image: "redis:latest"
    container_name: "redis_container"
    ports:
      - "6379:6379"
    environment:
      - REDIS_HOST=localhost
      - REDIS_PORT=6379

  # atemu_api-dev:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile # Specify your Dockerfile if needed
  #   container_name: atemu_api-dev
  #   ports:
  #     - "8000:8000"
  #   volumes:
  #     - .:/app # Mount current directory to /app in container
  #   env_file:
  #     - .env
  #   working_dir: /app
  #   command: yarn workspace api-service start:dev

  # atemu_onchain-queue-dev:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile # Specify your Dockerfile if needed
  #   container_name: atemu_onchain-queue-dev
  #   ports:
  #     - "8080:8080"
  #   volumes:
  #     - .:/app # Mount current directory to /app in container
  #   env_file:
  #     - .env
  #   working_dir: /app
  #   command: yarn workspace onchain-queue start:dev

  # onchain_worker_dev:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile # Specify your Dockerfile if needed
  #   container_name: onchain_worker_dev
  #   ports:
  #     - "8090:8090"
  #   volumes:
  #     - .:/app # Mount current directory to /app in container
  #   env_file:
  #     - .env
  #   working_dir: /app
  #   command: yarn workspace onchain-worker start:dev

#   mongo:
#     image: mongo:7.0.14
#     networks:
#       - app-network
#     restart: always
#     environment:
#       - HOST=mongo
#     volumes:
#       - mongo_data:/data/db
#       - mongo_log:/data/log
#     ports:
#       - 127.0.0.1:27018:27017
#     user: '1000:1000'


# secrets:
#   db_path:
#     file: ./secrets/DB_PATH.txt

# volumes:
#   node_modules: {}
#   mongo_data: {}
#   mongo_log: {}

# networks:
#   app-network:
#     driver: bridge