version: '3.8'

volumes:
  redis-data:
  node_modules:
  mongo_data:
  mongo_log:

networks:
  app-network:
    driver: bridge

services:
  redis-atemu:
    container_name: redis-atemu
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - app-network
    restart: always

  mongo:
    image: mongo:7.0.14
    container_name: mongo_atemu
    networks:
      - app-network
    environment:
      - HOST=mongo
    volumes:
      - mongo_data:/data/db
      - mongo_log:/data/log
    ports:
      - 27019:27017

  atemu-service:
    container_name: atemu-service
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
      - "5050:5050"
      - "5051:5051"
      - "8089:8089"
      - "8090:8090"
      - "8091:8091"
    env_file:
      - .env
    volumes:
      - .:/app
    networks:
      - app-network
    restart: always
