export enum FuelEvents {
  TOTAL_ONLINE = 'TOTAL_ONLINE',
  CURRENT_POOL = 'CURRENT_POOL',
  TOTAL_POINT = 'TOTAL_POINT',
  CURRENT_JOINED_POOL = 'CURRENT_JOINED_POOL',
  CREATE_POOL_TX_HASH = 'CREATE_POOL_TX_HASH',
  WINNER = 'WINNER',
}
